## cartridge.properties for cartridge int_eshopworld_e2eautomation
#Fri Jul 8 13:37:37 CEST 2025
demandware.cartridges.int_eshopworld_e2eautomation.multipleLanguageStorefront=true
demandware.cartridges.int_eshopworld_e2eautomation.id=int_eshopworld_e2eautomation